finish chat history and make friend with random
DrNguyen2525/minasan pull request #3
Opened 2020-11-23 10:45 UTC by PhamVietCuong20160579

2020-11-23 16:50 UTC, DrNguyen2525 commented on client/src/redux/chat/chat.actions.js
> +  type: ChatActionTypes.CREATE_CONVERSASION_START,
conversation sai chính tả

2020-11-23 16:50 UTC, DrNguyen2525 commented on client/src/redux/chat/chat.actions.js
> +export const fetchRandom = () => ({
đổi thành `fetchSuggestedUsers` nhé, tương tự 2 hàm bên dưới và tên action

2020-11-23 16:50 UTC, DrNguyen2525 commented on client/src/redux/chat/chat.reducer.js
> +  random_chatter: [],
`suggestedUsers`

2020-11-23 16:50 UTC, DrNguyen2525 commented on client/src/redux/chat/chat.actions.js
> +export const createConversasion = (curr_id, aite_id) => ({
`currentUserId`, `partnerId`

2020-11-23 16:50 UTC, DrNguyen2525 commented on client/src/redux/chat/chat.reducer.js
> +    case ChatActionTypes.FETCH_CONVERSATIONS_FAILURE:
Tất cả các action xử lý failure chỉ cần gộp vào 1 chỗ thôi vì nó giống nhau hết, không cần viết riêng từng cái.
Tham khảo trong `user.reducer.js`

2020-11-24 08:16 UTC, duongle26 requested changes

2020-11-24 08:16 UTC, duongle26 commented on client/package.json
> +    "socket.io": "2.3.0",
it should be socket.io-client

2020-11-24 08:16 UTC, duongle26 commented on client/src/components/chat-history/chat-history.component.jsx
> +  // console.log(chat_history);
remove this

2020-11-24 08:16 UTC, duongle26 commented on client/src/components/chat-box/chat-box.component.jsx
> +  // console.log(user)
remove this

2020-11-24 08:16 UTC, duongle26 commented on client/src/modals/find-friends-modal/find-friends-modal.component.jsx
> +  // console.log(users)
remove this

2020-11-24 08:16 UTC, duongle26 commented on client/src/services/chat.services.js
> +  // console.log('hello')
remove this

2020-11-24 08:16 UTC, duongle26 commented on client/.env
> +REACT_APP_BASE_URL=http://localhost:4000
delete this file

2020-11-24 08:23 UTC, merged